@jwt1 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE3OTI4NDl9.Wor1YPg7EgAwCOykJnJWpsyhQUXBbZSaQjqQvkQXQJs
@jwt2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE2NDgxMDF9.V8v2p8HLAUXKVK0ATCLXcPXiGHtRJkUMAjXltmtMFEw
@jwt3 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE2NDY4Mjh9.2pHODrhpdXMiHQyDQi--bZV9tbmR2YNg54y1aRYCgq4

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "bsimpson",
  "email": "bart@bart.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Posts index
GET http://localhost:3000/posts.json

### Posts create
POST http://localhost:3000/posts.json
Authorization: Bearer {{jwt1}}
Content-Type: application/json

{
  "image_url": "https://frinkiac.com/img/S06E23/1193658.jpg",
  "description": "tree in backyard",
  "latitude": 41.968304,
  "longitude": -87.646540
}

### Post update
PATCH http://localhost:3000/posts/3.json
Authorization: Bearer {{jwt2}}
Content-Type: application/json

{
  "description": "Tree with tree house"
}