@jwt1 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQwNDE1NDN9.hqk8WNSfVHFDMrlvstOeOtP_kynZ914esGYc9xQ80ZA
@jwt2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE2NDgxMDF9.V8v2p8HLAUXKVK0ATCLXcPXiGHtRJkUMAjXltmtMFEw
@jwt3 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjMzMzk4MTV9.2KqiVmJMHYZK3qkK_IBjcyAIvBzjFIV8_cRQOFpVnBo

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "bsimpson",
  "email": "bart@bart.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


################## POSTS ######################


### Posts index
GET http://localhost:3000/posts.json

### Posts create
POST http://localhost:3000/posts.json
Authorization: Bearer {{jwt1}}
Content-Type: application/json

{
  "description": "Cool tree, I like it!",
  "latitude": 41.971707,
  "longitude": -87.654395
}

### Post Show
GET http://localhost:3000/posts/3.json

### Post update
PATCH http://localhost:3000/posts/12.json
Authorization: Bearer {{jwt1}}
Content-Type: application/json

{
  "description": "Testing user authorization on backend"
}

### Post Destroy
DELETE http://localhost:3000/posts/11.json

################## COMMENTS ####################

### Comments index
GET http://localhost:3000/comments.json

### Comments create
POST http://localhost:3000/comments.json
Content-Type: application/json

{
  "body": "Very Nice, I like the leaf color",
  "post_id": 7,
  "user_id": 2
}

### Comments update
PATCH http://localhost:3000/comments/4.json
Content-Type: application/json

{
  "body": "I'll visit this tree on my next adventure"
}

### Comments destroy
DELETE http://localhost:3000/comments/4.json


################ FOLLOWS ##################

### Create Follow (follow someone)
POST http://localhost:3000/follows.json
Authorization: Bearer {{jwt3}}
Content-Type: application/json

{
  "followed_user_id": 1
}

### Destroy Follow (Unfollow someone)
DELETE http://localhost:3000/follows/11.json
Authorization: Bearer {{jwt3}}